export const TIER_LIMITS = {
  TRIAL: {
    maxStudents:        100,
    maxStages:          3,
    maxDocumentTypes:   5,
    maxOfficers:        3,
    customBranding:     false,
    csvImport:          false,
    emailNotify:        false,
    multiSession:       false,
    apiAccess:          false,
    auditRetentionDays: 30,
    reports:            false,
  },
  STANDARD: {
    maxStudents:        5000,
    maxStages:          10,
    maxDocumentTypes:   Infinity,
    maxOfficers:        Infinity,
    customBranding:     true,
    csvImport:          true,
    emailNotify:        true,
    multiSession:       true,
    apiAccess:          false,
    auditRetentionDays: 365,
    reports:            'csv',
  },
  ENTERPRISE: {
    maxStudents:        Infinity,
    maxStages:          Infinity,
    maxDocumentTypes:   Infinity,
    maxOfficers:        Infinity,
    customBranding:     true,
    csvImport:          true,
    emailNotify:        true,
    multiSession:       true,
    apiAccess:          true,
    auditRetentionDays: Infinity,
    reports:            'csv+pdf',
  },
} as const
